# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_info', models.CharField(max_length=1000)),
                ('general_detail', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('item_spec', models.CharField(max_length=500)),
                ('delivery', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_logo', models.CharField(max_length=1000)),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.CharField(max_length=50)),
                ('item_status', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tac.Item'),
        ),
    ]
